### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by Mega-dotcom** [sensepost/gowitness#193]
**Describe the bug**

```
$ /root/go/bin/gowitness --debug nmap -N -f web_ports.xml -t 20
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x510100]

goroutine 1 [running]:
net/url.(*URL).String(0x0)
        /usr/lib/go-1.18/src/net/url/url.go:800 +0x40
github.com/sensepost/gowitness/cmd.glob..func4(0x1b672c0?, {0x11444bc?, 0x6?, 0x6?})
        /root/go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20230711101818-5797fbaee673/cmd/nmap.go:85 +0x2d4
github.com/spf13/cobra.(*Command).execute(0x1b672c0, {0xc000304900, 0x6, 0x6})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1b67b60)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/sensepost/gowitness/cmd.Execute()
        /root/go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20230711101818-5797fbaee673/cmd/root.go:50 +0x25
main.main()
        /root/go/pkg/mod/github.com/sensepost/gowitness@v0.0.0-20230711101818-5797fbaee673/main.go:14 +0x3c
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Information:**
 - OS: Linux XXX 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - gowitness:
 
```
gowitness: 2.5.0

git hash: dev
go version: dev
```

**Additional context**

**Comment by leonjza** [comment]
Can you share an example nmap to reproduce? Feel free to re-open once you do.
